### PR TITLE
Convert to camel case

### PR DESCRIPTION
**Pull request by wch**
This converts webdriver to camel case, as discussed in MangoTheCat/shinytest#62.

### CODE REVIEW

**Comment by wch** [comment]
I'm really glad you wrote all those unit tests!

**Comment by gaborcsardi** [comment]
No, I thank you for doing this menial work!

**Comment by wch** [comment]
This menial work has given me a reason to make around 100 commits in the last 24 hours, so my GitHub profile looks super-productive!

**Comment by gaborcsardi** [comment]
:) Yeah, although if you only care about the looks, see http://www.laurencegellert.com/software/github-graph-builder

**Pull request merged**
